// src/components/project/ProjectReports.jsx
import React, { useState, useEffect } from 'react';
import { FiDownload, FiFileText, FiBarChart2, FiCalendar, FiTrendingUp, FiDollarSign } from 'react-icons/fi';
import { useWorkspace } from '../../contexts/WorkspaceContext';

const ProjectReports = ({ projectId }) => {
  const { projects, currentProject } = useWorkspace();
  const [project, setProject] = useState(null);
  const [isExporting, setIsExporting] = useState(false);

  useEffect(() => {
    if (currentProject?.id === projectId) {
      setProject(currentProject);
    } else if (projects.length > 0) {
      const found = projects.find(p => p.id === projectId);
      setProject(found);
    }
  }, [projectId, currentProject, projects]);

  const exportAsPDF = () => {
    setIsExporting(true);
    // Create printable content
    const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Project Report - ${project?.name}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; }
          h1 { color: #0A2F44; }
          .header { border-bottom: 2px solid #0A2F44; margin-bottom: 20px; }
          .section { margin-bottom: 30px; }
          .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; }
          .label { font-weight: bold; color: #666; }
          .value { color: #333; }
          table { width: 100%; border-collapse: collapse; margin-top: 15px; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          th { background-color: #f2f2f2; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Project Report: ${project?.name}</h1>
          <p>Generated: ${new Date().toLocaleString()}</p>
        </div>
        
        <div class="section">
          <h2>Project Information</h2>
          <div class="info-grid">
            <div><span class="label">Project Type:</span> <span class="value">${project?.project_type}</span></div>
            <div><span class="label">Location:</span> <span class="value">${project?.location || 'Not specified'}</span></div>
            <div><span class="label">Design Standard:</span> <span class="value">${project?.design_standard}</span></div>
            <div><span class="label">Status:</span> <span class="value">${project?.status}</span></div>
            <div><span class="label">Created:</span> <span class="value">${new Date(project?.created_at).toLocaleDateString()}</span></div>
            <div><span class="label">Last Updated:</span> <span class="value">${new Date(project?.updated_at).toLocaleDateString()}</span></div>
          </div>
        </div>
        
        <div class="section">
          <h2>Description</h2>
          <p>${project?.description || 'No description provided'}</p>
        </div>
        
        <div class="section">
          <h2>Design Summary</h2>
          <p>Design works will be listed here once created.</p>
        </div>
        
        <div class="section">
          <h2>Team Members</h2>
          <p>Team members will be listed here.</p>
        </div>
        
        <hr />
        <p style="text-align: center; color: #999; font-size: 12px;">
          Generated by StructAI - Structural Design Platform
        </p>
      </body>
      </html>
    `;
    
    const win = window.open();
    win.document.write(printContent);
    win.document.close();
    win.print();
    setIsExporting(false);
  };

  const exportAsExcel = () => {
    setIsExporting(true);
    // Create CSV content
    const headers = ['Property', 'Value'];
    const rows = [
      ['Project Name', project?.name || ''],
      ['Project Type', project?.project_type || ''],
      ['Location', project?.location || 'Not specified'],
      ['Design Standard', project?.design_standard || 'Eurocode'],
      ['Status', project?.status || 'active'],
      ['Created Date', new Date(project?.created_at).toLocaleDateString()],
      ['Last Updated', new Date(project?.updated_at).toLocaleDateString()],
      ['Description', project?.description || 'No description provided']
    ];
    
    const csvContent = [headers, ...rows].map(row => row.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${project?.name || 'project'}_report.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    setIsExporting(false);
  };

  if (!project) {
    return <div className="text-center py-8">Loading project data...</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold text-[#02090d] dark:text-white">Project Reports</h2>
          <p className="text-sm text-[#6b7280] dark:text-[#9ca3af]">
            Export project data and design reports
          </p>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-white dark:bg-[#1f2937] rounded-xl shadow-lg p-6 border border-[#e5e7eb] dark:border-[#374151]">
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm text-[#6b7280]">Designs</span>
            <FiBarChart2 className="text-[#0A2F44]" />
          </div>
          <p className="text-2xl font-bold text-[#02090d] dark:text-white">0</p>
          <p className="text-xs text-[#9ca3af] mt-1">Total designs created</p>
        </div>
        <div className="bg-white dark:bg-[#1f2937] rounded-xl shadow-lg p-6 border border-[#e5e7eb] dark:border-[#374151]">
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm text-[#6b7280]">Team Members</span>
            <FiUsers className="text-[#0A2F44]" />
          </div>
          <p className="text-2xl font-bold text-[#02090d] dark:text-white">0</p>
          <p className="text-xs text-[#9ca3af] mt-1">Project members</p>
        </div>
        <div className="bg-white dark:bg-[#1f2937] rounded-xl shadow-lg p-6 border border-[#e5e7eb] dark:border-[#374151]">
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm text-[#6b7280]">Last Active</span>
            <FiCalendar className="text-[#0A2F44]" />
          </div>
          <p className="text-2xl font-bold text-[#02090d] dark:text-white">
            {new Date(project.updated_at).toLocaleDateString()}
          </p>
        </div>
      </div>

      {/* Export Options */}
      <div className="bg-white dark:bg-[#1f2937] rounded-xl shadow-lg border border-[#e5e7eb] dark:border-[#374151] p-6">
        <h3 className="text-md font-semibold text-[#02090d] dark:text-white mb-4">Export Options</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <button
            onClick={exportAsPDF}
            disabled={isExporting}
            className="flex items-center justify-center space-x-3 p-4 border-2 border-dashed border-[#e5e7eb] dark:border-[#374151] rounded-xl hover:border-[#0A2F44] transition-colors"
          >
            <FiFileText className="text-2xl text-red-500" />
            <div className="text-left">
              <p className="font-medium text-[#02090d] dark:text-white">Export as PDF</p>
              <p className="text-xs text-[#6b7280]">Download project report as PDF</p>
            </div>
            <FiDownload className="text-[#6b7280]" />
          </button>
          <button
            onClick={exportAsExcel}
            disabled={isExporting}
            className="flex items-center justify-center space-x-3 p-4 border-2 border-dashed border-[#e5e7eb] dark:border-[#374151] rounded-xl hover:border-[#0A2F44] transition-colors"
          >
            <FiFileText className="text-2xl text-green-500" />
            <div className="text-left">
              <p className="font-medium text-[#02090d] dark:text-white">Export as CSV</p>
              <p className="text-xs text-[#6b7280]">Download project data as CSV</p>
            </div>
            <FiDownload className="text-[#6b7280]" />
          </button>
        </div>
      </div>

      {/* Design Summary */}
      <div className="bg-white dark:bg-[#1f2937] rounded-xl shadow-lg border border-[#e5e7eb] dark:border-[#374151] p-6">
        <h3 className="text-md font-semibold text-[#02090d] dark:text-white mb-4">Design Summary</h3>
        <div className="text-center py-8">
          <FiTrendingUp className="text-4xl text-[#9ca3af] mx-auto mb-2" />
          <p className="text-[#6b7280]">No designs created yet</p>
          <p className="text-xs text-[#9ca3af] mt-1">Designs will appear here once created</p>
        </div>
      </div>
    </div>
  );
};

export default ProjectReports;